### ISSUE TITLE
Error creating instance_template because both network and subnet are present

### ISSUE THREAD

**Issue by bpicolo** [terraform-google-modules/terraform-google-bastion-host#107]
### TL;DR

I hit an error when terraform tried to create the instance_template due to both network and subnet being provided. It seems like this is the module's intent? (Both are currently required variables)

```
│ Error: exactly one of network or subnetwork must be provided
│
│   with module.bastion.module.iap_bastion.module.instance_template.google_compute_instance_template.tpl,
│   on .terraform/modules/bastion.iap_bastion.instance_template/modules/instance_template/main.tf line 58, in resource "google_compute_instance_template" "tpl":
│   58: resource "google_compute_instance_template" "tpl" {
```

### Expected behavior

Was hoping this would create the bastion as intended, but I hit the issue above. I can't say entirely with confidence that this isn't user error, but I seem to be following the basic example as written

### Terraform Configuration

```hcl
module "iap_bastion" {
  source  = "terraform-google-modules/bastion-host/google"
  version = "5.0.0"

  project      = var.project
  zone         = var.zone
  machine_type = "e2-small"
  network      = var.network # in this case, self_link for the default network
  subnet       = var.subnet # in this case, self_link for the default us-east4 subnet


  members = local.developers
}
```

### Terraform Version

```sh
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.19.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

**Comment by bharathkkb** [comment]
@bpicolo Are you still running into this? I am wondering if variables are actually getting passed in via `var.network` and `var.subnet`?

**Comment by bpicolo** [comment]
@bharathkkb  not trying anymore, but definitely the case last time I tried!
