### ISSUE TITLE
Referenced Google module `vm/instance-template` which is enforcing hashicorp/google < 6

### ISSUE THREAD

**Issue by zaphod72** [terraform-google-modules/terraform-google-bastion-host#210]
https://github.com/terraform-google-modules/terraform-google-bastion-host/blob/3cb05d34485fcc915f3ea4a44c68bf4bd1da5bd3/main.tf#L47

references
```
  source  = "terraform-google-modules/vm/google//modules/instance_template"
  version = "~> 11.0"
```

which has
https://github.com/terraform-google-modules/terraform-google-vm/blob/0cf3225e2f347794e0f9f50ffc36cad17845101c/modules/instance_template/versions.tf#L22
```
    google-beta = {
      source  = "hashicorp/google-beta"
      version = ">= 5.5, < 6"
    }
```

Needs https://github.com/terraform-google-modules/terraform-google-vm/pull/400 to be merged :/

**Comment by zaphod72** [comment]
The terraform-google-vm PR has been merged.

**Comment by RoopeHakulinen** [comment]
Just echoing here that this is very much needed as currently it is not really possible to use google-beta v6 in a stack that uses this module.

**Comment by DucretJe** [comment]
Would it be possible to release a new version of this module? As @zaphod72 it's merged in `main` but not usable directly since 7.1.0 is still pointing to VM 11.0

https://github.com/terraform-google-modules/terraform-google-bastion-host/blob/v7.1.0/main.tf#L47

**Comment by zaphod72** [comment]
@RoopeHakulinen @DucretJe 
Workaround
```
module "bastion" {
  source  = "git::https://github.com/terraform-google-modules/terraform-google-bastion-host.git?ref=release-please--branches--master"
  ...
```
