### ISSUE TITLE
Bastion under a Region and not unser a Zone

### ISSUE THREAD

**Issue by meirhazon2** [terraform-google-modules/terraform-google-bastion-host#24]
Hello,
Can I have the bastion under a region? I have tried and it didnt work.
Is there a way?
Thanks so much,
Meir

**Comment by morgante** [comment]
GCP VMs are always deployed to a particular zone (within a region), so you have to choose your zone.

**Comment by dinvlad** [comment]
It's possible to create [Regional Instance Groups](https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups) - would that be something this module could add?

**Comment by dinvlad** [comment]
Sorry for spam :) I see that `bastion-group` module does create a regional group.
