### ISSUE TITLE
Support MIGs

### ISSUE THREAD

**Issue by onetwopunch** [terraform-google-modules/terraform-google-bastion-host#27]
We should create a module that implements a managed instance group and an internal load balancer in case bastions need high availability.

**Comment by onetwopunch** [comment]
Turns out that tunnelling through IAP doesn't work when the target is an internal load balancer

**Comment by morgante** [comment]
@onetwopunch If you still have to choose a specific instance to tunnel to, what is the use of the MIG?

**Comment by onetwopunch** [comment]
@morgante Admittedly it’s much more useful behind a load balancer, which I thought would work when I first started, but by itself the auto heal capability makes it worth it for HA. You can still effectively load balance client side by randomly choosing an instance as part of the MIG as I showed in the README. Also this module lays the groundwork to allow a load balancer once gcloud SDK does support it, or if the user decides not to use IAP at all, but just OS Login. Since the MIG self_link is output, users can integrate it into their own load balancer. Thoughts?
