### ISSUE TITLE
Module seem to be broken after v2.8.0

### ISSUE THREAD

**Issue by chanuka-techo** [terraform-google-modules/terraform-google-bastion-host#58]
I have been having issues connecting to a Bastion server made with `v2.10.0`

```
ERROR: (gcloud.beta.compute.start-iap-tunnel) Error while connecting [4003: 'failed to connect to backend'].
```

So I tried the last known good version, `v2.7.0` and everything in between. Turns out `v2.8.0` is the latest that works for me.

The firewall is properly created by all versions, so I'm not sure what's up. Some other places on the Internet addressing the issue suggest IAP being a special snowflake in certain regions. If it helps, I'm trying in `us-central1-a`. Will update if I find out more.

**Comment by onetwopunch** [comment]
Hi @chanuka-techo I just spun up a new bastion with the latest version in `us-central1-a` and everything works fine. I know you mentioned the firewall rule is correct, but if the instance is up, SSH is listening and the firewall rule is correct, the tunnel should be able to connect to the backend. Could you paste your configuration of the bastion-host here please?

**Comment by onetwopunch** [comment]
Closing issue due to lack of response
