### ISSUE TITLE
Complete support for terraform v0.14

### ISSUE THREAD

**Issue by jonbuffington** [terraform-google-modules/terraform-google-bastion-host#68]
Thanks for publishing release v2.10.1  as we are migrating to terraform v0.14. Unfortunately, release v2.10.1 does not completely support terraform v0.14. Line <https://github.com/terraform-google-modules/terraform-google-bastion-host/blob/1c88a0ccd58a5221e2203b2c2a21953dbdef6579/main.tf#L47> references a dependency that needs to be updated to >= [6.0.0](https://github.com/terraform-google-modules/terraform-google-vm/releases/tag/v6.0.0).

Relevant output from `terraform init --upgrade=true`:
```
Error: Unsupported Terraform Core version

  on .terraform/modules/bastion.instance_template/modules/instance_template/versions.tf line 18, in terraform:
  18:   required_version = ">=0.12.6, <0.14"

Module module.bastion.module.instance_template (from
terraform-google-modules/vm/google//modules/instance_template) does not
support Terraform version 0.14.2. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
```

**Comment by ryuheechul** [comment]
Just curious, if there is any update on this, as it appear to be no activities on the issue and the PR.

**Comment by onetwopunch** [comment]
This is now unblocked and I'm working on a fix this week

**Comment by jonbuffington** [comment]
@onetwopunch Thank you!
