### ISSUE TITLE
Block use of project-wide SSH keys on VM instance

### ISSUE THREAD

**Issue by kostacasa** [terraform-google-modules/terraform-google-bastion-host#80]
Hi,

We are using this module with great success, thank you for putting it together! In order to harden the configuration as much as possible, I was wondering if it would be possible to disable use of project-wide of SSH keys on the provisioned VM instance. Right now it's enabled by default and I did not see a way to turn the blocking on. If you don't think that would be a reasonable default, it would still be helpful to expose it as an additional input variable so that users can choose whether that makes sense for them:

```hcl
resource "google_compute_instance" "default" {
  name         = "bastion-vm"
  metadata = {
+     block-project-ssh-keys = var.block-project-ssh-keys
  }
}
```

**Comment by onetwopunch** [comment]
Thanks for bringing this issue up. We are fairly resource constrained at the moment, but if you would like to make a PR, someone will be able to review it soon.
