### ISSUE TITLE
Complete support for terraform v0.15

### ISSUE THREAD

**Issue by xylene314** [terraform-google-modules/terraform-google-bastion-host#87]
Hi Team,
Can we get support for Terraform 0.15?

**Comment by morgante** [comment]
What doesn't work in Terraform 0.15?

**Comment by xylene314** [comment]
@morgante Was thinking if we have support for 0.15 for this module?

**Comment by morgante** [comment]
Terraform 0.15 should already be supported. Just go ahead and try it.
